<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:33',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-22 11:02:33',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:33',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-09-10 05:49:36',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-09-10 05:49:36',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2021-07-22 11:02:33',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2021-07-22 11:06:00',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2021-07-22 11:06:01',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2021-07-22 11:06:01',
                'updated_at' => '2021-07-28 05:21:32',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => 'Home',
                'url' => '/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-07-22 11:14:04',
                'updated_at' => '2021-09-10 16:41:58',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 17,
                'menu_id' => 2,
                'title' => 'Profile Kelurahan',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-07-22 11:26:09',
                'updated_at' => '2021-09-10 16:41:58',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => 'Blog',
                'url' => '/blog',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-07-22 11:26:38',
                'updated_at' => '2021-09-10 16:42:00',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 20,
                'menu_id' => 2,
                'title' => 'Data Kelurahan',
                'url' => '/data-kelurahan',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2021-07-22 14:23:18',
                'updated_at' => '2021-09-10 16:48:13',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 23,
                'menu_id' => 2,
                'title' => 'Visi dan Misi',
                'url' => '/visi-dan-misi',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 17,
                'order' => 1,
                'created_at' => '2021-09-10 16:41:52',
                'updated_at' => '2021-09-10 16:44:44',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 24,
                'menu_id' => 2,
                'title' => 'Pemerintah Kelurahan',
                'url' => '/pemerintah-kelurahan',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 17,
                'order' => 2,
                'created_at' => '2021-09-10 16:43:09',
                'updated_at' => '2021-09-10 16:45:18',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 25,
                'menu_id' => 2,
                'title' => 'Badan Permusaywaratan Kelurahan',
                'url' => '/badan-permusaywaratan-kelurahan',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 17,
                'order' => 3,
                'created_at' => '2021-09-10 16:44:23',
                'updated_at' => '2021-09-10 16:44:38',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}